name: "HelloWorldPipeline"

on:
  push:
    branches:
      - master
      - production

jobs:
  print_message:
    runs-on: ubuntu-latest
    steps:
      - name: "Display Greeting"
        #run: echo "Hello, World!"
        run: echo "Hello World - $(date)"
